trigger:
  - master

resources:
  - repo: self

variables:
  # Define variables for Docker image and ACR
  dockerRegistryServiceConnection: 'myACRServiceConnection'
  kubernetesServiceConnection: 'myAKSServiceConnection'
  imageRepository: 'flask-app'
  containerRegistry: 'myctnreg5300.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
#  tag: 'latest'

stages:
  - stage: Build
    displayName: Stage-Build
    jobs:
      - job: Build
        displayName: Job-Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: StepTask-Build_img_and_push_to_ACR
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
          - publish: $(Build.SourcesDirectory)/k8s
            artifact: k8s_files

  - stage: Deploy
    displayName: Stage-Deploy_to_Kubernetes
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Job-Deploy
        environment: 'Development'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: k8s_files

                - task: Kubernetes@1
                  displayName: StepTask-Set_kubectl_context
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
                    command: login

                - script: |
                    sed -i 's/myctnreg5300.azurecr.io\/flask-app:latest/myctnreg5300.azurecr.io\/flask-app:$(Build.BuildId)/' $(Pipeline.Workspace)/k8s_files/deployment.yml
                  displayName: StepScript-Update_img_tag_in_k8s_manifest

                - task: Kubernetes@1
                  displayName: StepTask-Deploy_to_k8s
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
                    command: apply
                    arguments: '-f $(Pipeline.Workspace)/k8s_files/deployment.yml'
                    secretType: dockerRegistry
                    containerRegistryType: Azure Container Registry
                    containerRegistry: $(containerRegistry)
                    namespace: default
